export enum ApiErrorCodes {
  // Validation
  VALIDATION_FAILED = 'VALIDATION.FAILED',
  VALIDATION_INVALID_UUID = 'VALIDATION.INVALID_UUID',
  VALIDATION_INVALID_BIRTH_DATE = 'VALIDATION.INVALID_BIRTH_DATE',
  VALIDATION_IS_EMAIL = 'VALIDATION.IS_EMAIL',
  VALIDATION_REQUIRED = 'VALIDATION.REQUIRED',

  // Auth
  AUTH_UNAUTHORIZED = 'AUTH.UNAUTHORIZED',
  AUTH_INVALID_CREDENTIALS = 'AUTH.INVALID_CREDENTIALS',
  AUTH_FORBIDDEN = 'AUTH.FORBIDDEN',
  AUTH_REFRESH_TOKEN_MISSING = 'AUTH.REFRESH_TOKEN_MISSING',
  AUTH_SESSION_COMPROMISED = 'AUTH.SESSION_COMPROMISED',
  AUTH_TOKEN_INVALID = 'AUTH.TOKEN_INVALID',
  AUTH_TOKEN_EXPIRED = 'AUTH.TOKEN_EXPIRED',
  AUTH_LOGOUT_FAILED = 'AUTH.LOGOUT_FAILED',

  // Users
  USER_NOT_FOUND = 'USER.NOT_FOUND',
  USER_EMAIL_IN_USE = 'USER.EMAIL_IN_USE',
  USER_PHONE_IN_USE = 'USER.PHONE_IN_USE',
  USER_ALREADY_EXISTS = 'USER.ALREADY_EXISTS',

  // Organizations
  ORGANIZATION_NOT_FOUND = 'ORGANIZATION.NOT_FOUND',
  ORGANIZATION_ALREADY_EXISTS = 'ORGANIZATION.ALREADY_EXISTS',
  ORGANIZATION_NOT_APPROVED = 'ORGANIZATION.NOT_APPROVED',
  ORGANIZATION_ALREADY_APPROVED = 'ORGANIZATION.ALREADY_APPROVED',
  ORGANIZATION_ALREADY_REJECTED = 'ORGANIZATION.ALREADY_REJECTED',

  // Children
  CHILD_NOT_FOUND = 'CHILD.NOT_FOUND',
  CHILD_LIMIT_REACHED = 'CHILD.LIMIT_REACHED',
  CHILD_ACCESS_DENIED = 'CHILD.ACCESS_DENIED',
  CHILD_ALREADY_ASSIGNED = 'CHILD.ALREADY_ASSIGNED',
  CHILD_INVALID_TYPE = 'CHILD.INVALID_TYPE',
  CHILD_DUPLICATE = 'CHILD.DUPLICATE',

  // Grades
  GRADE_NOT_FOUND = 'GRADE.NOT_FOUND',
  GRADE_ALREADY_EXISTS = 'GRADE.ALREADY_EXISTS',

  // Classes
  CLASS_NOT_FOUND = 'CLASS.NOT_FOUND',
  CLASS_ALREADY_EXISTS = 'CLASS.ALREADY_EXISTS',
  CLASS_FULL = 'CLASS.FULL',

  // Evaluations
  EVALUATION_NOT_FOUND = 'EVALUATION.NOT_FOUND',
  EVALUATION_ATTEMPT_NOT_FOUND = 'EVALUATION.ATTEMPT_NOT_FOUND',
  EVALUATION_ATTEMPT_LOCKED = 'EVALUATION.ATTEMPT_LOCKED',
  EVALUATION_MAX_ATTEMPTS = 'EVALUATION.MAX_ATTEMPTS_REACHED',
  EVALUATION_DIMENSION_MISSING = 'EVALUATION.DIMENSION_MISSING',
  EVALUATION_DUPLICATE_DIMENSIONS = 'EVALUATION.DUPLICATE_DIMENSIONS',
  EVALUATION_DUPLICATE_ANSWERS = 'EVALUATION.DUPLICATE_ANSWERS',
  EVALUATION_INVALID_TRANSITION = 'EVALUATION.INVALID_TRANSITION',
  EVALUATION_SLOT_NOT_FOUND = 'EVALUATION.SLOT_NOT_FOUND',
  EVALUATION_INVALID_QUESTION = 'EVALUATION.INVALID_QUESTION',
  EVALUATION_INVALID_ANSWER = 'EVALUATION.INVALID_ANSWER',
  EVALUATION_NOT_SUITABLE_AGE = 'EVALUATION.NOT_SUITABLE_AGE',
  EVALUATION_NOT_AVAILABLE = 'EVALUATION.NOT_AVAILABLE',

  // Payments
  PAYMENT_NOT_FOUND = 'PAYMENT.NOT_FOUND',
  PAYMENT_FAILED = 'PAYMENT.FAILED',
  PAYMENT_EXPIRED = 'PAYMENT.EXPIRED',
  PAYMENT_MAX_RETRIES = 'PAYMENT.MAX_RETRIES',
  PAYMENT_INVALID_PROVIDER = 'PAYMENT.INVALID_PROVIDER',
  PAYMENT_CURRENCY_NOT_SUPPORTED = 'PAYMENT.CURRENCY_NOT_SUPPORTED',
  PAYMENT_WEBHOOK_INVALID = 'PAYMENT.WEBHOOK_INVALID',
  PAYMENT_WEBHOOK_MISSING = 'PAYMENT.WEBHOOK_MISSING',
  PAYMENT_PROVIDER_UNAVAILABLE = 'PAYMENT.PROVIDER_UNAVAILABLE',
  PAYMENT_INVALID_JSON = 'PAYMENT.INVALID_JSON',

  // Deals
  DEAL_NOT_FOUND = 'DEAL.NOT_FOUND',
  DEAL_CLOSED = 'DEAL.CLOSED',
  DEAL_DEADLINE_PASSED = 'DEAL.DEADLINE_PASSED',
  DEAL_DUPLICATE_PROPOSAL = 'DEAL.DUPLICATE_PROPOSAL',
  DEAL_CANNOT_CREATE = 'DEAL.CANNOT_CREATE',
  DEAL_PROPOSAL_NOT_FOUND = 'DEAL.PROPOSAL_NOT_FOUND',
  DEAL_PROPOSAL_INVALID_STATE = 'DEAL.PROPOSAL_INVALID_STATE',
  DEAL_INVALID_STATE = 'DEAL.INVALID_STATE',
  DEAL_ATTENDANCE_REQUIRED = 'DEAL.ATTENDANCE_REQUIRED',

  // Activities
  ACTIVITY_NOT_FOUND = 'ACTIVITY.NOT_FOUND',
  ACTIVITY_HAS_DEALS = 'ACTIVITY.HAS_DEALS',

  // Transfers
  TRANSFER_NOT_FOUND = 'TRANSFER.NOT_FOUND',
  TRANSFER_ALREADY_RESOLVED = 'TRANSFER.ALREADY_RESOLVED',
  TRANSFER_INVALID_CHILD_TYPE = 'TRANSFER.INVALID_CHILD_TYPE',

  // Notifications
  NOTIFICATION_NOT_FOUND = 'NOTIFICATION.NOT_FOUND',
  NOTIFICATION_EMAIL_REQUIRED = 'NOTIFICATION.EMAIL_REQUIRED',

  // Sessions
  SESSION_EXPIRED = 'SESSION.EXPIRED',
  SESSION_NOT_FOUND = 'SESSION.NOT_FOUND',

  // Capacity
  CAPACITY_NOT_FOUND = 'CAPACITY.NOT_FOUND',
  CAPACITY_ACCESS_DENIED = 'CAPACITY.ACCESS_DENIED',
  CAPACITY_ALREADY_PENDING = 'CAPACITY.ALREADY_PENDING',
  CAPACITY_INVALID_STATE = 'CAPACITY.INVALID_STATE',

  // Teachers
  TEACHER_NOT_FOUND = 'TEACHER.NOT_FOUND',
  TEACHER_ALREADY_EXISTS = 'TEACHER.ALREADY_EXISTS',

  // Database
  DB_UNIQUE_VIOLATION = 'DB.UNIQUE_VIOLATION',
  DB_FOREIGN_KEY_VIOLATION = 'DB.FOREIGN_KEY_VIOLATION',
  DB_NOT_NULL_VIOLATION = 'DB.NOT_NULL_VIOLATION',
  DB_CHECK_VIOLATION = 'DB.CHECK_VIOLATION',
  DB_ERROR = 'DB.ERROR',

  // Rate limiting
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT.EXCEEDED',

  // Internal
  INTERNAL_SERVER_ERROR = 'INTERNAL.UNEXPECTED',
}
