export enum ApiErrorCodes {
  VALIDATION_ERROR = 'VALIDATION_ERROR',

  UNAUTHORIZED = 'UNAUTHORIZED',

  FORBIDDEN = 'FORBIDDEN',

  NOT_FOUND = 'NOT_FOUND',

  CONFLICT = 'CONFLICT',

  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',

  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',

  PHONE_ALREADY_EXISTS = 'PHONE_ALREADY_EXISTS',

  PAYMENT_FAILED = 'PAYMENT_FAILED',

  PAYMENT_EXPIRED = 'PAYMENT_EXPIRED',

  CLASS_FULL = 'CLASS_FULL',

  CHILD_ALREADY_ASSIGNED = 'CHILD_ALREADY_ASSIGNED',

  SESSION_EXPIRED = 'SESSION_EXPIRED',
}
